### ISSUE TITLE
Уточнение по функции DrawChick() - (поворот в другую сторону)

### ISSUE THREAD

**Issue by Pugovkina** [Nielra/Library#1]
Эльвира, в личном сообщении, вы сказали, что поворот в другую сторону, необходимо отрицательным сделать параметр sizeX. 
В описании функции вы пишите  sizeY - Размер высоты Цыпленка (Если отрицательно, то смотрит вправо). 
Какой именно параметр отвечает за разворот цыплёнка?

**Comment by Nielra** [comment]
Здравствуйте. В описании - ошибка (мой косяк). Если делать отрицательным sizeY, то цыпленок будет вверх ногами

**Comment by Nielra** [comment]
Еще добавила пример с движением Exzample_move.cpp
